# Generated by Django 4.2.7 on 2025-11-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON')], default='excel', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='job_type',
            field=models.CharField(choices=[('single', 'Single Person'), ('batch', 'Batch Processing'), ('company_websites', 'Company Websites')], default='batch', max_length=20),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='content_source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn Profile'), ('company_website', 'Company Website'), ('google_search', 'Google Search Results')], default='linkedin', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='core.company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.company'),
        ),
    ]
